apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- ../../base/
- namespace.yaml

patches: 
- path: course-app-deployment.yaml
- patch: |-
    - op: add
      path: /spec/replicas
      value: 2
  target:
    kind: Dragonfly
- patch: |-
    - op: remove
    path: /
  target:
    kind: Dragonfly
