apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- ../../base/course-app
- course-app-deployment.yaml
- course-app-service.yaml
- course-app-ingress.yaml
- namespace.yaml
- course-app-hpa.yaml

patches: 
- path: course-app-deployment.yaml
- path: course-app-service.yaml
- path: course-app-ingress.yaml
- patch: |-
    - op: add
      path: /spec/replicas
      value: 2
  target:
    kind: Dragonfly