apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - course-app-deployment.yaml
  - course-app-service.yaml

configMapGenerator:
  - name: app-config
    literals:
      - APP_STORE=redis
      - APP_REDIS_URL=redis://dragonfly-sample.dragonfly-operator-system:6379/0
