apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - app-config.yaml
  - course-app/course-app.yaml
  - course-app/ingress.yaml
  - course-app/course-app-hpa.yaml
  - dragonfly/dragonfly.yaml